# Generated by Django 5.1.2 on 2024-11-19 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('menu', '0008_alter_product_subcategory'),
        ('vendor', '0005_alter_openinghour_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('product_desc', models.TextField(blank=True, null=True)),
                ('full_specification', models.TextField(blank=True, default='')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(upload_to='store/products/%Y/%m/%d')),
                ('is_available', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(blank=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('barcode', models.CharField(max_length=16, unique=True)),
                ('qty', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.category')),
                ('deposit_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='inventory.deposit')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_products', to='menu.category')),
                ('tax_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='inventory.tax')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendor.vendor')),
            ],
        ),
    ]
