# Generated by Django 5.1.2 on 2024-11-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0005_alter_product_deposit_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deposit_category',
        ),
    ]
