# Generated by Django 5.1.2 on 2024-11-25 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_tax_tax_percentage'),
        ('unified', '0006_remove_product_deposit_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deposit_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='inventory.deposit'),
        ),
    ]
