# Generated by Django 5.1.2 on 2024-11-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0007_product_deposit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='store/products/uploads'),
        ),
    ]
