# Generated by Django 5.1.2 on 2024-12-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_tax_tax_percentage'),
        ('unified', '0009_alter_product_barcode_product_unique_vendor_barcode'),
        ('vendor', '0005_alter_openinghour_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('vendor', 'slug'), name='unique_vendor_slug'),
        ),
    ]
