# Generated by Django 5.1.2 on 2024-12-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0010_product_unique_vendor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
    ]
