# Generated by Django 5.1.2 on 2024-12-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0016_alter_productgallery_image_and_more'),
        ('vendor', '0006_vendor_fssai_number_vendor_gst_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('vendor', 'slug'), name='unique_vendor_slug_category'),
        ),
    ]
