# Generated by Django 5.1.2 on 2024-12-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0018_product_hsn_number_alter_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, default='N/A', max_length=25, null=True),
        ),
    ]
