# Generated by Django 5.1.2 on 2024-12-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_tax_tax_percentage'),
        ('unified', '0019_alter_product_barcode'),
        ('vendor', '0006_vendor_fssai_number_vendor_gst_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_vendor_barcode',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', 'N/A'), _negated=True), fields=('vendor', 'barcode'), name='unique_vendor_barcode_non_na'),
        ),
    ]
