# Generated by Django 5.1.2 on 2024-12-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_tax_tax_percentage'),
        ('unified', '0020_remove_product_unique_vendor_barcode_and_more'),
        ('vendor', '0006_vendor_fssai_number_vendor_gst_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_vendor_barcode_non_na',
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('vendor', 'barcode'), name='unique_vendor_barcode'),
        ),
    ]
