# Generated by Django 5.1.2 on 2024-12-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0021_remove_product_unique_vendor_barcode_non_na_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
