# Generated by Django 5.1.2 on 2024-12-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0022_product_model_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
