# Generated by Django 5.1.2 on 2024-12-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0023_alter_product_model_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Liters'), ('ml', 'Milliliters')], default='pcs', help_text='Unit type for the product', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Quantity in selected unit type', max_digits=10),
        ),
    ]
