# Generated by Django 5.1.2 on 2024-12-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0024_product_unit_type_alter_product_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Quantity in selected unit type', max_digits=10),
        ),
    ]
