# Generated by Django 5.1.2 on 2025-04-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0029_alter_product_cost_price_alter_product_regular_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_vendor_slug_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='vendor',
        ),
        migrations.AddField(
            model_name='category',
            name='category_code',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('category_code',), name='unique_category_code'),
        ),
    ]
