# Generated by Django 5.1.2 on 2025-05-08 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0030_remove_category_unique_vendor_slug_category_and_more'),
        ('vendor', '0011_remove_adbanner_store_type_remove_adbanner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='store_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.storetype'),
        ),
    ]
