# Generated by Django 5.1.2 on 2025-05-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0031_category_store_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='vendor_subcategory_reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
