# Generated by Django 5.1.2 on 2025-06-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0032_category_vendor_subcategory_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_top_collection',
            field=models.BooleanField(default=False),
        ),
    ]
