# Generated by Django 5.1.2 on 2025-06-20 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0033_product_is_top_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBrowsePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='browse-banners/')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='unified.category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryBrowseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('section_type', models.CharField(choices=[('product_slider', 'Product Slider'), ('subcategory_slider', 'Subcategory Slider'), ('brand_slider', 'Brand Slider'), ('custom_heading', 'Custom Heading Only')], max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('browse_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='unified.categorybrowsepage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unified.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='unified.categorybrowsesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='unified.categorybrowsesection')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unified.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
