# Generated by Django 5.1.2 on 2025-06-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0034_categorybrowsepage_categorybrowsesection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybrowsesection',
            name='section_type',
            field=models.CharField(choices=[('product_slider', 'Product Slider'), ('subcategory_slider', 'Subcategory Slider'), ('brand_slider', 'Brand Slider'), ('image_slider', 'Image Slider'), ('custom_heading', 'Custom Heading Only')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='productassignment',
            name='product',
        ),
        migrations.AddField(
            model_name='productassignment',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='unified.product'),
        ),
    ]
