# Generated by Django 5.1.2 on 2025-06-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0035_alter_categorybrowsesection_section_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoryassignment',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='subcategoryassignment',
            name='subcategory',
            field=models.ManyToManyField(blank=True, null=True, to='unified.category'),
        ),
    ]
