# Generated by Django 5.1.2 on 2025-06-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0036_remove_subcategoryassignment_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productassignment',
            name='product',
            field=models.ManyToManyField(blank=True, to='unified.product'),
        ),
        migrations.AlterField(
            model_name='subcategoryassignment',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='unified.category'),
        ),
    ]
