# Generated by Django 5.1.2 on 2025-06-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0037_alter_productassignment_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorybrowsepage',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='categorybrowsepage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the browse page in the category list. Lower numbers appear first.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_code',
            field=models.CharField(help_text="Enter category code(e.g. 'GROC', 'BEV')", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='vendor_subcategory_reference_id',
            field=models.IntegerField(blank=True, help_text='This field is for a subcategory specific to a vendor. Leave it empty when adding a main category.', null=True),
        ),
        migrations.AlterField(
            model_name='categorybrowsesection',
            name='title',
            field=models.CharField(help_text='Enter a title for the section (e.g., Lowest Price Deal on Appliances, Shop by Category, etc).', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Recommended resolution: 500x500 pixels. Ensure the image is in square format for best results', upload_to='store/products/uploads'),
        ),
        migrations.AlterField(
            model_name='productassignment',
            name='product',
            field=models.ManyToManyField(blank=True, help_text='Select products to display in this section.', to='unified.product'),
        ),
    ]
