# Generated by Django 5.1.2 on 2025-06-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0038_alter_categorybrowsepage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorybrowsepage',
            options={'ordering': ['order']},
        ),
    ]
