# Generated by Django 5.1.2 on 2025-06-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0039_alter_categorybrowsepage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
