# Generated by Django 5.1.2 on 2025-07-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0040_product_company_product_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended resolution: 500x500 pixels. Ensure the image is in square format for best results', null=True, upload_to='store/products/uploads'),
        ),
    ]
