# Generated by Django 5.1.2 on 2025-07-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0041_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, help_text='Recommended resolution: 500x500 pixels. Ensure the image is in square format for best results', upload_to='store/products/uploads'),
            preserve_default=False,
        ),
    ]
