# Generated by Django 5.1.2 on 2025-07-04 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0042_alter_product_image'),
        ('vendor', '0011_remove_adbanner_store_type_remove_adbanner_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCloneTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=300)),
                ('product_name', models.CharField(max_length=200)),
                ('product_desc', models.TextField(blank=True, null=True)),
                ('full_specification', models.TextField(blank=True, default='')),
                ('hsn_number', models.CharField(blank=True, max_length=8, null=True)),
                ('model_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('category_name', models.CharField(max_length=100)),
                ('subcategory_name', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=25, null=True)),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('tax_category_name', models.CharField(max_length=100)),
                ('deposit_category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_type', models.CharField(default='pcs', max_length=15)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('product_size', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_products', to='vendor.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'slug')},
            },
        ),
    ]
