# Generated by Django 5.1.2 on 2025-07-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0043_productclonetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productclonetable',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='productclonetable',
            name='company',
        ),
        migrations.RemoveField(
            model_name='productclonetable',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='productclonetable',
            name='full_specification',
        ),
        migrations.RemoveField(
            model_name='productclonetable',
            name='hsn_number',
        ),
        migrations.RemoveField(
            model_name='productclonetable',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='productclonetable',
            name='product_desc',
        ),
        migrations.RemoveField(
            model_name='productclonetable',
            name='product_size',
        ),
        migrations.RemoveField(
            model_name='productclonetable',
            name='sales_price',
        ),
        migrations.RemoveField(
            model_name='productclonetable',
            name='subcategory_name',
        ),
    ]
