# Generated by Django 5.1.2 on 2025-07-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0044_remove_productclonetable_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybrowsesection',
            name='section_type',
            field=models.CharField(choices=[('product_slider', 'Product Slider'), ('image_slider', 'Image Slider')], max_length=50),
        ),
    ]
