# Generated by Django 5.1.2 on 2025-07-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0046_alter_product_product_name_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_code',
            field=models.CharField(help_text="Enter category code(e.g. 'GROC', 'BEV')", max_length=350, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=400),
        ),
    ]
