# Generated by Django 5.1.2 on 2025-07-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0049_variantattribute_productvariantgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantgroup',
            name='attribute',
            field=models.ManyToManyField(to='unified.variantattributevalue'),
        ),
        migrations.DeleteModel(
            name='ProductVariantOption',
        ),
    ]
