# Generated by Django 5.1.2 on 2025-07-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0050_productvariantgroup_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantgroup',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantgroup',
            name='stock',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
    ]
