# Generated by Django 5.1.2 on 2025-07-17 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0051_alter_productvariantgroup_price_and_more'),
        ('vendor', '0011_remove_adbanner_store_type_remove_adbanner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='unified.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productattribute',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('name', 'category')},
        ),
    ]
