# Generated by Django 5.1.2 on 2025-07-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0052_productattribute_category_productattribute_vendor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variantattributevalue',
            unique_together={('attribute', 'value', 'product')},
        ),
    ]
