# Generated by Django 5.1.2 on 2025-07-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0053_alter_variantattributevalue_unique_together'),
        ('vendor', '0011_remove_adbanner_store_type_remove_adbanner_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(condition=models.Q(('vendor__isnull', True)), fields=('name', 'category'), name='unique_global_attribute'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(condition=models.Q(('vendor__isnull', False)), fields=('name', 'category', 'vendor'), name='unique_vendor_attribute'),
        ),
    ]
