# Generated by Django 5.1.2 on 2025-07-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0054_alter_productattribute_unique_together_and_more'),
        ('vendor', '0011_remove_adbanner_store_type_remove_adbanner_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productattribute',
            name='unique_global_attribute',
        ),
        migrations.RemoveConstraint(
            model_name='productattribute',
            name='unique_vendor_attribute',
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(condition=models.Q(('vendor__isnull', True)), fields=('name', 'category'), name='unique_global_name_category'),
        ),
    ]
