# Generated by Django 5.1.2 on 2025-07-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified', '0056_remove_productattribute_unique_global_name_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantgroup',
            name='sku',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
