# Generated by Django 5.1.2 on 2024-11-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_tax_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='fooditem',
        ),
    ]
