# Generated by Django 5.1.2 on 2024-11-06 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_remove_cart_fooditem'),
        ('menu', '0005_category_is_active_category_parent_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.product'),
            preserve_default=False,
        ),
    ]
