# Generated by Django 5.1.2 on 2025-07-17 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_cart_product'),
        ('unified', '0050_productvariantgroup_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_variant_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unified.productvariantgroup'),
        ),
    ]
