# Generated by Django 5.1.2 on 2024-11-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttransaction',
            name='deposit_category',
        ),
    ]
