# Generated by Django 5.1.2 on 2024-11-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_producttransaction_deposit_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransaction',
            name='deposit_category',
            field=models.CharField(default=1, editable=False, max_length=125),
            preserve_default=False,
        ),
    ]
