# Generated by Django 5.1.2 on 2024-12-03 14:02

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receipt',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
