# Generated by Django 5.1.2 on 2024-12-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_transaction_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_dt',
            field=models.DateTimeField(),
        ),
    ]
