# Generated by Django 5.1.2 on 2024-12-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_alter_transaction_transaction_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_dt',
            field=models.DateTimeField(editable=False),
        ),
    ]
