# Generated by Django 5.1.2 on 2024-12-03 14:11

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_alter_transaction_deposit_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receipt',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
