# Generated by Django 5.1.2 on 2024-12-03 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_alter_transaction_receipt'),
        ('vendor', '0006_vendor_fssai_number_vendor_gst_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='deposit_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'CASH'), ('DEBIT/CREDIT', 'DEBIT/CREDIT'), ('EBT', 'EBT')], editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='products',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=7),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_sale',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=7),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_dt',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vendor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
