# Generated by Django 5.1.2 on 2025-01-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_customerinfo_transaction_customer_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='gstin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
