# Generated by Django 5.1.2 on 2025-01-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_customerinfo_address_customerinfo_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='qty',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Quantity in selected unit type', max_digits=10),
        ),
    ]
