# Generated by Django 5.1.2 on 2025-01-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_alter_producttransaction_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, null=True),
        ),
    ]
