# Generated by Django 5.1.2 on 2025-01-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_alter_producttransaction_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_sale',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
