# Generated by Django 5.1.2 on 2024-12-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_superadmin',
            new_name='is_superuser',
        ),
    ]
