# Generated by Django 5.1.2 on 2025-07-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='assets/imgs/vendor/vendor-header-bg.png)', null=True, upload_to='users/cover_photos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default-profile-new.png', null=True, upload_to='users/profile_pictures'),
        ),
    ]
