# Generated by Django 5.1.2 on 2025-07-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userprofile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='vendor/profile and cover default/vendor-header-bg.png', null=True, upload_to='users/cover_photos'),
        ),
    ]
