# Generated by Django 5.1.2 on 2025-07-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userprofile_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='vendor/profile_and_cover_default/vendor-header-bg.png', null=True, upload_to='users/cover_photos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='vendor/profile_and_cover_default/default-profile-new.png', null=True, upload_to='users/profile_pictures'),
        ),
    ]
