# Generated by Django 5.1.2 on 2025-06-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventads',
            options={'ordering': ['-created_at'], 'verbose_name': 'Event Ad', 'verbose_name_plural': 'Event Ads'},
        ),
        migrations.AddField(
            model_name='event',
            name='home_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
