# Generated by Django 5.1.2 on 2025-06-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_alter_eventads_options_event_home_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='home_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, null=True),
        ),
    ]
