# Generated by Django 5.1.2 on 2025-06-26 09:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_alter_event_home_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='home_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
    ]
