# Generated by Django 5.1.2 on 2024-11-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax_category',
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='tax',
            constraint=models.UniqueConstraint(fields=('tax_category', 'tax_percentage'), name='unique_tax_category_percentage'),
        ),
    ]
