# Generated by Django 5.1.2 on 2025-06-28 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_tax_tax_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax_category',
            field=models.CharField(help_text='Enter a tax category name (e.g., VAT, GST, Service Tax).', max_length=32),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Enter the tax percentage (e.g., 5.00 for 5%).', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
