# Generated by Django 5.1.2 on 2025-04-29 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unified', '0030_remove_category_unique_vendor_slug_category_and_more'),
        ('vendor', '0011_remove_adbanner_store_type_remove_adbanner_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='category_banners/')),
                ('category', models.OneToOneField(limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='unified.category')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cover_page_banners/')),
                ('link', models.URLField(blank=True, null=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
    ]
