# Generated by Django 5.1.2 on 2025-04-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorybanner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
