# Generated by Django 5.1.2 on 2025-04-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_categorybanner_is_active_homepagebanner_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebanner',
            name='image',
            field=models.ImageField(help_text='Recommended resolution: 1920x442 pixels. Ensure the image is in landscape orientation for best results.', upload_to='cover_page_banners/'),
        ),
        migrations.AlterField(
            model_name='homepagebanner',
            name='link',
            field=models.URLField(blank=True, help_text='Enter the full URL, including domain (e.g., https://www.example.com).', null=True),
        ),
    ]
