# Generated by Django 5.1.2 on 2025-04-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_homepagebanner_image_alter_homepagebanner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorybanner',
            name='link',
            field=models.URLField(default=1, help_text='Enter the full URL, including domain (e.g., https://www.example.com).'),
            preserve_default=False,
        ),
    ]
