# Generated by Django 5.1.2 on 2025-04-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_categorybanner_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybanner',
            name='image',
            field=models.ImageField(help_text='Recommended resolution: 768x450 pixels. Ensure the image is in landscape orientation for best results.', upload_to='category_banners/'),
        ),
    ]
