# Generated by Django 5.1.2 on 2025-04-30 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_categorybanner_image'),
        ('unified', '0030_remove_category_unique_vendor_slug_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybanner',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='unified.category'),
        ),
    ]
