# Generated by Django 5.1.2 on 2025-04-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_categorybanner_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagebanner',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
