# Generated by Django 5.1.2 on 2025-06-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_homepagebanner_options_homepagebanner_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('logic', models.CharField(choices=[('popular', 'Popular Products'), ('low_price', 'Lowest Price Guarantee'), ('latest', 'Latest Products'), ('top_collection', 'Flickbasket Top Collection')], max_length=50)),
            ],
        ),
    ]
