# Generated by Django 5.1.2 on 2025-06-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_productcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcollection',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
