# Generated by Django 5.1.2 on 2025-06-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_productcollection_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcollection',
            name='name',
            field=models.CharField(help_text='Enter a collection name that matches the logic (e.g., Lowest Price Guarantee).', max_length=255),
        ),
    ]
