# Generated by Django 5.1.2 on 2025-07-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_alter_productcollection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcollection',
            name='logic',
            field=models.CharField(choices=[('low_price', 'Lowest Price Guarantee'), ('latest', 'Latest Products')], max_length=50),
        ),
    ]
