# Generated by Django 5.1.2 on 2024-11-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
