# Generated by Django 5.1.2 on 2024-11-12 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_product_subcategory'),
        ('orders', '0003_alter_order_tax_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedfood',
            name='fooditem',
        ),
        migrations.AddField(
            model_name='orderedfood',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.product'),
            preserve_default=False,
        ),
    ]
