# Generated by Django 5.1.2 on 2024-11-20 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderedfood_fooditem_orderedfood_product'),
        ('unified', '0002_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedfood',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unified.product'),
        ),
    ]
