# Generated by Django 5.1.2 on 2024-12-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedfood',
            options={'verbose_name': 'Ordered Product', 'verbose_name_plural': 'Ordered Products'},
        ),
    ]
