# Generated by Django 5.1.2 on 2025-06-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedfood',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Paid', 'Paid'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Processing', max_length=15),
        ),
    ]
