# Generated by Django 5.1.2 on 2025-06-29 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderedfood_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
