# Generated by Django 5.1.2 on 2025-07-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedfood',
            name='variant_info',
            field=models.JSONField(blank=True, help_text='Snapshot of variant details at the time of order', null=True),
        ),
    ]
